import requests
import os
from dotenv import load_dotenv
from pathlib import Path

load_dotenv(Path(__file__).resolve().parent.parent / ".env")

CLIENT_ID = os.getenv("YOUTUBE_CLIENT_ID")
CLIENT_SECRET = os.getenv("YOUTUBE_CLIENT_SECRET")
REDIRECT_URI = os.getenv("YOUTUBE_REDIRECT_URI")

def get_access_token(code: str) -> str:
    res = requests.post(
        "https://oauth2.googleapis.com/token",
        data={
            "grant_type": "authorization_code",
            "code": code,
            "redirect_uri": REDIRECT_URI,
            "client_id": CLIENT_ID,
            "client_secret": CLIENT_SECRET,
        }
    )
    data = res.json()
    print(f"YouTube token 응답: {data}")
    return data["access_token"]

def create_playlist(access_token: str, name: str) -> str:
    res = requests.post(
        "https://www.googleapis.com/youtube/v3/playlists",
        headers={"Authorization": f"Bearer {access_token}"},
        params={"part": "snippet,status"},
        json={
            "snippet": {"title": name, "description": "Generated by Festival Playlist Generator"},
            "status": {"privacyStatus": "private"}
        }
    )
    data = res.json()
    print(f"YouTube playlist 생성: {data}")
    return data["id"]

def search_video(access_token: str, artist: str, track: str) -> str | None:
    res = requests.get(
        "https://www.googleapis.com/youtube/v3/search",
        headers={"Authorization": f"Bearer {access_token}"},
        params={
            "part": "snippet",
            "q": f"{artist} {track} official",
            "type": "video",
            "maxResults": 1
        }
    )
    items = res.json().get("items", [])
    if items:
        return items[0]["id"]["videoId"]
    return None

def add_video(access_token: str, playlist_id: str, video_id: str):
    requests.post(
        "https://www.googleapis.com/youtube/v3/playlistItems",
        headers={"Authorization": f"Bearer {access_token}"},
        params={"part": "snippet"},
        json={
            "snippet": {
                "playlistId": playlist_id,
                "resourceId": {"kind": "youtube#video", "videoId": video_id}
            }
        }
    )

def export_to_youtube(access_token: str, playlist_name: str, playlist: list[dict]) -> str:
    playlist_id = create_playlist(access_token, playlist_name)

    for item in playlist:
        for track in item["tracks"]:
            video_id = search_video(access_token, item["artist"], track)
            if video_id:
                add_video(access_token, playlist_id, video_id)

    return playlist_id